apiVersion: v1
kind: Namespace
metadata: 
  name: zomato-ns
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zomato-rc #name of the rc
spec:
  replicas: 2
  selector: 
    app: zomato-app #it is used to identify the pods and the label should also be label
  template: #here we will write pod information
    metadata:
      name: zomato-pod
      labels:
        app: zomato-app
    spec:
      containers:
        - name: zomato-container
          image: kastrov/zomato
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: LoadBalancer
  selector:
    app: zomato-app
  ports:
    - port: 80
      targetPort: 3000